apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 5m0s
  url: oci://ghcr.io/nginx/charts/nginx-ingress
  ref:
    semver: "^2.1.0"